### ISSUE TITLE
Empty response on reading Webhooks from Argus due to owner mismatch

### ISSUE THREAD

**Issue by utsavbatra5** [xmidt-org/ancla#54]
We are facing issue reading hooks posted to argus.
1. The hooks are posted using tr1d1um "/hook" and the owner is passed as "user" during this post request. 

2. While reading the hooks, the owner is passed as empty string in the get call and hence all the hooks are filtered out on basis of owner.
https://github.com/xmidt-org/argus/blob/main/chrysom/client.go#L397 

I tried passing X-Midt-Owner as header in the post request but it is always overwritten to "user" in POST and "" in GET request. 

@joe94 @kcajmagic Can you please check and help us resolve this issue?

Also, we are using the latest version of tr1d1um, argus and ancla for this testing.

**Comment by joe94** [comment]
1) The reason why the owner is always set to `user` is that Ancla uses the bascule token (of the HTTP request asking to add a webhook) principal field as the owner. Since you're likely using our default basic auth key (`dXNlcjpwYXNz`), the decoded username is `user`. 
https://github.com/xmidt-org/ancla/blob/316db2859189a7676454d5bfb67d17a2f1f35827/transport.go#L115

2) It's okay for the owner value to be empty when fetching all items within a bucket. This is because you can make a request in "admin" mode to Argus. Making a request in admin mode means that you can get access to items you don't own. 

So, to fix that issue you'll have to do two things:
A) Use JWTs instead of basic tokens in Tr1d1um and Caduceus when communicating with Argus (i.e. https://github.com/xmidt-org/tr1d1um/blob/main/tr1d1um.yaml#L145). Ensure that your JWT has a capability that will signal Argus that all requests using this JWT will run in "admin" mode.

B) Configure Argus with the capability you chose in A). You can find more instructions on this here -> https://github.com/xmidt-org/argus/blob/main/argus.yaml#L159

**Comment by joe94** [comment]
@utsavbatra5 were you able to resolve the issue you were seeing?

**Comment by Sachin4403** [comment]
Hi @joe94,

We had tried to use the themis as JWT token issuer but we are getting an exception here
https://github.com/xmidt-org/bascule/blob/ebaddc7fde12947854a32641945200fda36cc54d/acquire/bearer.go#L141-L144
 
## Problem

 Themis will be returning the token in the response body, In the bearer.go it will be expecting it in a struct and it will throw the exception
https://github.com/xmidt-org/bascule/blob/ebaddc7fde12947854a32641945200fda36cc54d/acquire/bearer.go#L77-L80

**Comment by joe94** [comment]
Hey @Sachin4403, yeah that's something I've run into before as well and I had made an issue for it https://github.com/xmidt-org/ancla/issues/58

I'll give it a try and keep you posted 👍

**Comment by joe94** [comment]
@Sachin4403, I know this is a blocker for you guys so I'm prioritizing implementing a fix. I'll keep you updated on #58

**Comment by joe94** [comment]
@Sachin4403, I found a fix and ran some tests to verify it in both Tr1d1um and Caduceus. I'll be making a new version of these services soon (today).

**Comment by Sachin4403** [comment]
Thant for the update @joe94

**Comment by joe94** [comment]
@Sachin4403, I just released new versions for Tr1d1um and Caduceus 🎉 
I also updated https://github.com/xmidt-org/xmidt so you can see how the different moving parts work together:
- Modified Argus config so that Themis tokens will be considered admin tokens: https://github.com/xmidt-org/xmidt/blob/cad8710674f4c1934b6e515e2a5fd404fddb4986/deploy/docker-compose/docker-compose.yml#L102
- Modified Caduceus and Tr1d1um to use that Themis token to interact with Argus:
  -  https://github.com/xmidt-org/caduceus/blob/e3de0fea1a29c4ae0e5079278be75c930c5fc784/deploy/packaging/caduceus_spruce.yaml#L279  
  -  https://github.com/xmidt-org/tr1d1um/blob/b52294b9ebe6da4e125b914f3e836c029c766800/deploy/packaging/tr1d1um_spruce.yaml#L156

**Comment by Sachin4403** [comment]
Thanks @joe94.

**Comment by joe94** [comment]
@Sachin4403, LMK if this solved the issue you were seeing so I can close this. Thanks!

**Comment by Sachin4403** [comment]
Hi @joe94 
This issue is solved by using the JWT token.
